/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import databaseConnection.CLogin;
import javax.swing.JOptionPane;

/**
 *
 * @author usr
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        fondo_login = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Iniciar_sesion_texto = new javax.swing.JLabel();
        Correo_electronico_texto = new javax.swing.JLabel();
        Contrseña_texto = new javax.swing.JLabel();
        Ingreso_correo_electronico = new javax.swing.JTextField();
        Nota_registro_texto = new javax.swing.JLabel();
        Boton_ingresar = new javax.swing.JButton();
        Ingreso_contraseña = new javax.swing.JPasswordField();
        Boton_registrar = new javax.swing.JButton();
        Boton_continuar_google = new javax.swing.JButton();
        Boton_continuar_facebook = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1040));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo_login.setBackground(new java.awt.Color(204, 204, 204));
        fondo_login.setForeground(new java.awt.Color(204, 204, 204));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo_web-removebg-preview.png"))); // NOI18N

        Iniciar_sesion_texto.setFont(new java.awt.Font("OCR A Extended", 0, 50)); // NOI18N
        Iniciar_sesion_texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Iniciar_sesion_texto.setText("Iniciar Sesión");

        Correo_electronico_texto.setFont(new java.awt.Font("OCR A Extended", 0, 20)); // NOI18N
        Correo_electronico_texto.setText("Correo Electronico");

        Contrseña_texto.setFont(new java.awt.Font("OCR A Extended", 0, 20)); // NOI18N
        Contrseña_texto.setText("Contraseña");

        Ingreso_correo_electronico.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        Ingreso_correo_electronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingreso_correo_electronicoActionPerformed(evt);
            }
        });

        Nota_registro_texto.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        Nota_registro_texto.setText("No tienes una cuenta?, registrate");

        Boton_ingresar.setFont(new java.awt.Font("OCR A Extended", 0, 20)); // NOI18N
        Boton_ingresar.setText("Ingresar");
        Boton_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ingresarActionPerformed(evt);
            }
        });

        Ingreso_contraseña.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        Ingreso_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingreso_contraseñaActionPerformed(evt);
            }
        });

        Boton_registrar.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        Boton_registrar.setText("Registrar");
        Boton_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_registrarActionPerformed(evt);
            }
        });

        Boton_continuar_google.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        Boton_continuar_google.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo_google.png"))); // NOI18N
        Boton_continuar_google.setText("Continuar con Google");
        Boton_continuar_google.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_continuar_googleActionPerformed(evt);
            }
        });

        Boton_continuar_facebook.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        Boton_continuar_facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo_facebook.png"))); // NOI18N
        Boton_continuar_facebook.setText("Continuar con Facebook");

        javax.swing.GroupLayout fondo_loginLayout = new javax.swing.GroupLayout(fondo_login);
        fondo_login.setLayout(fondo_loginLayout);
        fondo_loginLayout.setHorizontalGroup(
            fondo_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondo_loginLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(285, 285, 285))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondo_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fondo_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondo_loginLayout.createSequentialGroup()
                        .addComponent(Boton_registrar)
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondo_loginLayout.createSequentialGroup()
                        .addComponent(Boton_ingresar)
                        .addGap(317, 317, 317))))
            .addGroup(fondo_loginLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(fondo_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nota_registro_texto)
                    .addComponent(Iniciar_sesion_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correo_electronico_texto)
                    .addComponent(Ingreso_correo_electronico, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contrseña_texto)
                    .addComponent(Ingreso_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147))
            .addGroup(fondo_loginLayout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addGroup(fondo_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Boton_continuar_facebook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Boton_continuar_google, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(240, 240, 240))
        );
        fondo_loginLayout.setVerticalGroup(
            fondo_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondo_loginLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Iniciar_sesion_texto)
                .addGap(40, 40, 40)
                .addGroup(fondo_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nota_registro_texto)
                    .addComponent(Boton_registrar))
                .addGap(18, 18, 18)
                .addComponent(Correo_electronico_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Ingreso_correo_electronico, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(Contrseña_texto)
                .addGap(18, 18, 18)
                .addComponent(Ingreso_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Boton_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Boton_continuar_google, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Boton_continuar_facebook, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        getContentPane().add(fondo_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 760, 1080));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ingreso_correo_electronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingreso_correo_electronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingreso_correo_electronicoActionPerformed

    private void Boton_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ingresarActionPerformed
        String email = Ingreso_correo_electronico.getText();
        String password = new String(Ingreso_contraseña.getPassword());

        boolean loginExitoso = CLogin.verificarLogin(email, password);

        if (loginExitoso) {
            
            //JOptionPane.showMessageDialog(null, "ID del usuario: " + CLogin.userId);
            if(CLogin.userId == 1){
                SuperUser windowAdmin = new SuperUser();
                windowAdmin.setVisible(true);
                dispose();
            } else{
                HomePage ventanaHomePage = new HomePage(CLogin.userId);
                ventanaHomePage.setVisible(true);
                dispose();
            }
            
        } else {

            JOptionPane.showMessageDialog(null, "Correo incorrecto o contraseña incorrecta");
        }
    }//GEN-LAST:event_Boton_ingresarActionPerformed

    private void Boton_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_registrarActionPerformed
        Register ventanaRegister = new Register();
        ventanaRegister.setVisible(true);
        dispose();
    }//GEN-LAST:event_Boton_registrarActionPerformed

    private void Boton_continuar_googleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_continuar_googleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_continuar_googleActionPerformed

    private void Ingreso_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingreso_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingreso_contraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_continuar_facebook;
    private javax.swing.JButton Boton_continuar_google;
    private javax.swing.JButton Boton_ingresar;
    private javax.swing.JButton Boton_registrar;
    private javax.swing.JLabel Contrseña_texto;
    private javax.swing.JLabel Correo_electronico_texto;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPasswordField Ingreso_contraseña;
    private javax.swing.JTextField Ingreso_correo_electronico;
    private javax.swing.JLabel Iniciar_sesion_texto;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Nota_registro_texto;
    private javax.swing.JPanel fondo_login;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
